# Form implementation generated from reading ui file '.\third_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.dest = QtWidgets.QLabel(Form)
        self.dest.setObjectName("dest")
        self.verticalLayout.addWidget(self.dest, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.h_widget = QtWidgets.QWidget(Form)
        self.h_widget.setObjectName("h_widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.h_widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.src_widget = QtWidgets.QWidget(self.h_widget)
        self.src_widget.setObjectName("src_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.src_widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2.addWidget(self.src_widget, 0, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.table = QtWidgets.QTableWidget(self.h_widget)
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.table)
        self.verticalLayout.addWidget(self.h_widget)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setMinimumSize(QtCore.QSize(0, 35))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.path = QtWidgets.QLabel(self.widget)
        self.path.setMinimumSize(QtCore.QSize(50, 22))
        self.path.setText("")
        self.path.setObjectName("path")
        self.horizontalLayout.addWidget(self.path)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.cost = QtWidgets.QLabel(self.widget)
        self.cost.setMinimumSize(QtCore.QSize(30, 22))
        self.cost.setText("")
        self.cost.setObjectName("cost")
        self.horizontalLayout.addWidget(self.cost)
        self.calc_btn = QtWidgets.QPushButton(self.widget)
        self.calc_btn.setEnabled(True)
        self.calc_btn.setMinimumSize(QtCore.QSize(58, 22))
        self.calc_btn.setMaximumSize(QtCore.QSize(60, 16777215))
        self.calc_btn.setObjectName("calc_btn")
        self.horizontalLayout.addWidget(self.calc_btn)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Calculate"))
        self.title.setText(_translate("Form", "Enter the parameters"))
        self.dest.setText(_translate("Form", "Destination"))
        self.label_3.setText(_translate("Form", "Path:"))
        self.label_5.setText(_translate("Form", "Cost:"))
        self.calc_btn.setText(_translate("Form", "Calculate"))
